plugins {
	id 'groovy-gradle-plugin'
	id 'maven-publish'
	id 'net.swedz.deploy-inator' version '1.0.0'
}

group = 'net.swedz'
version = (System.getenv("DEPLOYINATOR_VERSION") ?: "0.0.0-local")
base {
	archivesName = project.artifact_name
}

logger.lifecycle("Deploy-Inator version ${version}")

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

tasks.named("jar") {
	from "LICENSE"
}

tasks.register("sourceJar", Jar) {
	group = "build"
	archiveClassifier.set("sources")
	from sourceSets.main.allJava
	from "LICENSE"
}

gradlePlugin {
	plugins {
		it.register("deployInator") {
			id = "net.swedz.deploy-inator"
			implementationClass = "net.swedz.deployinator.DeployInatorPlugin"
		}
	}
}

repositories {
	mavenLocal()
	mavenCentral()
	gradlePluginPortal()
}

dependencies {
	implementation "org.apache.groovy:groovy:5.0.6"
	implementation "me.modmuss50:mod-publish-plugin:2.1.1"
}

apply from: 'deploy.gradle'
